name: Shell Commands
on: [push]
jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello World"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python
  run-windodws-commands:
    runs-on: windows-latest
    steps:
      - name: Show Current directory Powershell
        run: Get-Location
      - name: Show Current directory Bash
        run: pwd
        shell: bash
      